from enum import Enum


class SqlServerTypes(Enum):
    BIGINT = "bigint"
    BINARY = "binary"
    BIT = "bit"
    CHAR = "char"
    DATE = "date"
    DATETIME = "datetime"
    DATETIME2 = "datetime2"
    DATETIMEOFFSET = "datetimeoffset"
    DECIMAL = "decimal"
    FLOAT = "float"
    IMAGE = "image"
    INT = "int"
    MONEY = "money"
    NCHAR = "nchar"
    NUMERIC = "numeric"
    NVARCHAR = "nvarchar"
    NTEXT = "ntext"
    REAL = "real"
    SMALLDATETIME = "smalldatetime"
    SMALLINT = "smallint"
    SMALLMONEY = "smallmoney"
    TEXT = "text"
    TIME = "time"
    TINYINT = "tinyint"
    UNIQUEIDENTIFIER = "uniqueidentifier"
    VARBINARY = "varbinary"
    VARCHAR = "varchar"
    XML = "xml"
